### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by emps** [sane/sails-hook-babel#16]
after installing the hook and tring to lift getting this error im on sails 12.0.1
some problems with the paths

```
D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\o
ption-manager.js:364
    return presets.map(function (val) {
                   ^
Error: Couldn't find preset "es2015" relative to directory "D:\\projects\\myproject\\web-server\\api\\responses"
    at D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\op
tions\option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-c
ore\lib\transformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-cor
e\lib\transformation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-cor
e\lib\transformation\file\options\option-manager.js:307:14)
    at OptionManager.init (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\node_modules\babel-core\lib\tr
ansformation\file\options\option-manager.js:465:10)
    at compile (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\lib\node.js:81:45)
    at loader (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-register\lib\node.js:126:14)
    at Object.require.extensions.(anonymous function) [as .js] (D:\projects\myproject\web-server\node_modules\sails-hook-babel\node_modules\babel-re
gister\lib\node.js:136:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at D:\projects\myproject\web-server\node_modules\include-all\index.js:129:29
    at Array.forEach (native)
    at requireAll (D:\projects\myproject\web-server\node_modules\include-all\index.js:44:9)
```

**Comment by dangreen** [comment]
@emps as we can see in error message problem is in `babel-register` module
