### ISSUE TITLE
SyntaxError: Unexpected reserved word for import

### ISSUE THREAD

**Issue by IshantAgarwal** [sane/sails-hook-babel#5]
Even after installing this hook I am facing the same issue. I am  using nodejs and having the default configs specified for this hook.
Following is the stack trace.
SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Module._extensions..js (module.js:474:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jabong/projects/INDFAS/Jiesenberg/node_modules/sails-hook-babel/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jabong/projects/INDFAS/Jiesenberg/api/services/TestInterpreter.js:1:19)
    at Module._compile (module.js:456:26)
    at normalLoader (/home/jabong/projects/INDFAS/Jiesenberg/node_modules/sails-hook-babel/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/jabong/projects/INDFAS/Jiesenberg/node_modules/sails-hook-babel/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/lib/node_modules/sails/node_modules/include-all/index.js:129:29

**Comment by dangreen** [comment]
@IshantAgarwal it seems like you try to use babel 6 without presets. Which version of babel you are use ?
